---
title: "Speed dating"
author: "Kai Wang"
date: "2017/12/5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(data.table)
library(RSQLite)
library(dbplyr)
library(dplyr)
library(purrr)
library(ggplot2)

conn <- dbConnect(SQLite(), 'Desktop/FPA_FOD_20170508.sqlite')

# pull the fires table into RAM
fires <- tbl(conn, "Fires") %>% collect()

fires <- fires %>% na.omit()

print(object.size(fires), units = 'Gb')

fires <- fires %>% arrange(DISCOVERY_DATE, CONT_DATE)

fires$CONT_DATEymd <- as.Date(fires$CONT_DATE - 2458014.5, origin = '2017-09-18')

fires$DISCOVERY_DATEymd <- as.Date(fires$DISCOVERY_DATE - 2458014.5, origin = '2017-09-18')

firesplot <- fires %>% select(FIRE_SIZE, LATITUDE, LONGITUDE, CONT_DATEymd, DISCOVERY_DATEymd) %>% 
  na.omit() %>% data.frame()

load("~/STA523/Project-peppa_pig/fireplot.RData")

firesplot <- data.frame(firesplot)

days <- apply(firesplot, 1, function(x){
  if(x[4]!=x[5]){
    return(seq(as.Date(x[5]), as.Date(x[4]), by="days"))
  }
})

notoneday = which(lapply(days,is.null)==F)
duration = lapply(days, length) %>% unlist()

newdataframe <- firesplot[rep(seq_len(nrow(firesplot)), duration), ]
newdataframe$DISCOVERY_DATEymd <- (do.call("c", days)) %>% as.Date(origin = '1970-01-01')

allday <- rbind(newdataframe[,-4], firesplot[-notoneday,-4])

allday <- allday %>% arrange(DISCOVERY_DATEymd) 

year1992 <- allday[substr(allday$DISCOVERY_DATEymd,1,4) == '1992',]


library(ggmap)
library(animation)

npoints<- length(unique(year1992$DISCOVERY_DATEymd))

map<-get_map(location='united states', zoom=4, maptype = "terrain",
             source='google',color='color')

plotfire <- function(){
  for(i in 1:npoints){
    date <- as.Date(year1992[1, 4]) + i - 1
    take_df <- year1992[which(year1992$DISCOVERY_DATEymd == date), ]
    p <- ggmap(map) + geom_point(
      aes(x=LONGITUDE, y=LATITUDE, colour=FIRE_SIZE, size=FIRE_SIZE), 
      data=take_df, alpha=.5, na.rm = T)  + 
      scale_color_gradient(low="yellow", high="dark red") +
      ggtitle(date)
    print(p)
  }
}

saveGIF(plotfire())



```

##EDA
```{r}
summary(data)
```

```{r}
```

