---
title: "Wildfire"
author: "Peppa pig"
date: "12/10/2017"
output: pdf_document
---

```{r setup, include=FALSE}
library(data.table)
library(RSQLite)
library(dbplyr)
library(dplyr)
library(purrr)
library(ggmap)
library(ggplot2)
library(ggthemes)
library(animation)
```


```{r}
#download dataset and remove zip file afterwards
download.file(url = "https://storage.googleapis.com/kaggle-datasets/2478/4139/FPA_FOD_20170508.sqlite.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1513189819&Signature=myp%2BB6XkMNUOfxgOsXoJbjzfSigsiX1Ds9wa8datVuulb7qk8hr5vaDh6S%2Fim9%2FygU7V%2Fpgk%2Fw%2FiPNduZsS7%2F6BUu7Lv3TSfIhPib%2B%2F0y4iCpoiii2dc1T%2B%2F2e4qY0E74yaPRgVKDQcjj1CL%2F0gF55JLr0QdkwoY5qnSt09w%2B%2B%2Bg8ZVn5jvPslhvxZDUcDlDVZdB0O%2BSdrZyu%2Flh8prBw2v2TZAzhylhok0WfbqU4MGLnGqLDa89Nf%2Fhtk%2Ba3KzadSLm04Eiv7jIh2%2FTpaYfqLPjelAHcj1KQrqjs1EK9DjLHuIPpXz2Y%2BnHM3ZLnM2iGnTRMnp5LtHd%2BQNs9GscrA%3D%3D", destfile = "data.zip")

unzip("data.zip")

file.remove("data.zip")
```

```{r}
#load data
conn <- dbConnect(SQLite(), "FPA_FOD_20170508.sqlite")

# pull the fires table into RAM
fires <- tbl(conn, "Fires") %>% collect()

dbDisconnect(conn)

print(object.size(fires), units = 'Gb')

fires = fires %>% 
  select(FIRE_YEAR, DISCOVERY_DATE, DISCOVERY_DOY, DISCOVERY_TIME, STAT_CAUSE_CODE, STAT_CAUSE_DESCR, CONT_DATE, CONT_DOY, CONT_TIME, FIRE_SIZE, FIRE_SIZE_CLASS, LATITUDE, LONGITUDE, OWNER_CODE, OWNER_DESCR, STATE, COUNTY, FIPS_CODE, FIPS_NAME)

print(object.size(fires), units = 'Gb')

save(fires, file = "fires.Rdata")
```

```{r plotgif}
load("fires.Rdata")
fires <- fires %>% arrange(DISCOVERY_DATE, CONT_DATE)

# Add codes for DC and Puerto Rico to the default state lists
state.abb <- append(state.abb, c("DC", "PR"))
state.name <- append(state.name, c("District of Columbia", "Puerto Rico"))

# Map the state abbreviations to state names so we can join with the map data
fires$region <- map_chr(fires$STATE, function(x) { tolower(state.name[grep(x, state.abb)]) })

fires$CONT_DATEymd <- as.Date(fires$CONT_DATE - 2458014.5, origin = '2017-09-18')

fires$DISCOVERY_DATEymd <- as.Date(fires$DISCOVERY_DATE - 2458014.5, origin = '2017-09-18')

firesplot <- fires %>% select(FIRE_SIZE, LATITUDE, LONGITUDE, CONT_DATEymd, DISCOVERY_DATEymd, STATE, region) %>% na.omit() %>% data.frame()

# Get the us state map data
state_map <- map_data('state')

save(fires, file = "~/STA523/Project-peppa_pig/fires.RData")

save(firesplot, file = "~/STA523/Project-peppa_pig/firesplot.RData")

load("~/STA523/Project-peppa_pig/firesplot.RData")

firesplot <- data.frame(firesplot)

days <- apply(firesplot, 1, function(x){
  if(x[4]!=x[5]){
    return(seq(as.Date(x[5]), as.Date(x[4]), by="days"))
  }
})

notoneday = which(lapply(days,is.null)==F)
duration = lapply(days, length) %>% unlist()

newdataframe <- firesplot[rep(seq_len(nrow(firesplot)), duration), ]
newdataframe$DISCOVERY_DATEymd <- (do.call("c", days)) %>% as.Date(origin = '1970-01-01')

allday <- rbind(newdataframe[,-4], firesplot[-notoneday,-4])

allday <- allday %>% arrange(DISCOVERY_DATEymd) 

save(allday, file = "~/STA523/Project-peppa_pig/allday.RData")

plotfire <- function(State, year, month){
  
  if (is.null(month) == T){
    subset <- which(substr(allday$DISCOVERY_DATEymd,1,4) == as.character(year) & 
                    allday$STATE == State)
  } else {
    subset <- which(substr(allday$DISCOVERY_DATEymd,1,4) == as.character(year) & 
                    as.numeric(substr(allday$DISCOVERY_DATEymd,6,7)) == month & 
                    allday$STATE == State)
  }

  plotdata <- allday[subset, ]
  npoints<- length(unique(plotdata$DISCOVERY_DATEymd))
  
  if (npoints == 0){
    stop("Safe without a wildfire within this period")
  } else {
    p0 <- plotdata %>% 
    select(region) %>%
    left_join(state_map, by = 'region') %>%
    ggplot(aes(x = long, y = lat)) + 
    geom_polygon(fill= "lightblue") + 
    theme_map() + 
    coord_map('albers', lat0=30, lat1=40)+ guides(fill=FALSE) +
    ggtitle(paste0(State,sep="  ",sep='Year:', year, sep="  ", sep='Month:', month)) + 
    theme(plot.title = element_text(hjust = 0.5))
    
    for(i in 1:npoints){
    date <- as.Date(plotdata[1, 4]) + i - 1
    take_df <- plotdata[which(plotdata$DISCOVERY_DATEymd == date), ]
    p <- p0+ geom_point(
      aes(x=LONGITUDE, y=LATITUDE, colour=FIRE_SIZE, size=FIRE_SIZE), 
      data=take_df, alpha=.5, na.rm = T)  + theme(legend.position="none")+
      scale_color_gradient(low="red", high="dark red") +
      ggtitle(date)
    print(p)
  }
  }
}

State = 'NC'
year = 2015
month = 2
saveGIF(plotfire(State, year, month), movie.name = paste0(State,year,month,'.gif'))

```

```{r}

library(shiny)


shinyServer(function(input, output) {
  output$testgif = downloadHandler(
    filename = 'random.gif',
    content  = function(file) {
      saveGIF(
        for (i in 1:30) {
          plot(rnorm(100))
        }, movie.name = 'random.gif', interval = 0.1)
      file.rename('random.gif', file)
    })
})

shinyUI(basicPage(
  downloadButton("testgif")
))


ui <- basicPage(
    imageOutput("plot1"))

server <- function(input, output) {
    output$plot1 <- renderImage({
    # A temp file to save the output.
    # This file will be removed later by renderImage
    outfile <- tempfile(fileext='.gif')

    # now make the animation
    p = ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, 
      color = continent, frame = year)) + geom_point() + scale_x_log10()

    gg_animate(p,"outfile.gif")

    # Return a list containing the filename
     list(src = "outfile.gif",
         contentType = 'image/gif'
         # width = 400,
         # height = 300,
         # alt = "This is alternate text"
         )}, deleteFile = TRUE)}

shinyApp(ui, server)


shinyApp(
  ui = fluidPage(
    titlePanel("Wildfire 1992-2015"),
    sidebarLayout(
      sidebarPanel(
        helpText("Enter the state year and month to get gif of wildfires."),
        br(),
        textInput("State", "State Abbreviation", value = state.abb),
        br(),
        sliderInput("year", "Year", min = 1995, max = 2015, value = 1992),
        br(),
        sliderInput("month","Month", min = 1, max = 12, value = 1),
        br(),
        actionButton("go", "Get Gif!")
      ),
      
      mainPanel(
        uiOutput("links")
        #wellPanel(helpText('Remark: Used data is all from NYTimes Archive'))
      )
    )
  ),
  server = function(input, output, session)
  {
    #when click the button get articledata
    articledata = eventReactive(input$go, {
      get_nyt_archive(year = as.numeric(substr(input$datein, 1, 4)),
                       month = as.numeric(substr(input$datein, 6, 7)),
                       day = as.numeric(substr(input$datein, 9, 10)),
                       key = input$key)
            }
      )
    headline = eventReactive(input$go, {articledata()$headline})
    multimedia = eventReactive(input$go, {articledata()$multimedia})
    
    #events would be observed when click the button
    observeEvent(input$go,{
      }
      )
    
  }
)
```


```{r Shiny}
library(shiny)
library(leaflet)
library(RColorBrewer)
library(scales)
library(lattice)
library(dplyr)
library(ggplot2)
library(lubridate)

#REFERENCE: https://shiny.rstudio.com/gallery/superzip-example.html

maps = c(
  "OpenStreetMap" = "default",
  "OpenTopoMap" = "OpenTopoMap",
  "Esri.WorldTopoMap" = "Esri.WorldTopoMap",
  "Esri.WorldImagery" = "Esri.WorldImagery",
  "HERE.hybridDay" = "HERE.hybridDay",
  "NASAGIBS.ViirsEarthAtNight2012" = "NASAGIBS.ViirsEarthAtNight2012",
  "Stamen.Toner" = "Stamen.Toner",
  "Stamen.TonerLite" = "Stamen.TonerLite",
  "Stamen.TonerLines" = "Stamen.TonerLines",
  "CartoDB.Positron" = "CartoDB.Positron"
)

states = c(
  "All States" = "All",
  "Alabama" =	"AL",
  "Alaska" = "AK",
  "Arizona"	= "AZ",
  "Arkansas" = "AR",
  "California" = "CA",
  "Colorado" = "CO",
  "Connecticut" = "CT",
  "Delaware" = "DE",
  "District of Columbia" = "DC",
  "Florida" = "FL",
  "Georgia" = "GA",
  "Hawaii" = "HI",
  "Idaho" = "ID",
  "Illinois" = "IL",
  "Indiana" = "IN",
  "Iowa" = "IA",
  "Kansas" = "KS",
  "Kentucky" = "KY",
  "Louisiana" = "LA",
  "Maine" = "ME",
  "Maryland" = "MD",
  "Massachusetts" = "MA",
  "Michigan" = "MI",
  "Minnesota" = "MN",
  "Mississippi" = "MS",
  "Missouri" = "MO",
  "Montana" = "MT",
  "Nebraska" = "NE",
  "Nevada" = "NV",
  "New Hampshire" = "NH",
  "New Jersey" = "NJ",
  "New Mexico" = "NM",
  "New York" = "NY",
  "North Carolina" = "NC",
  "North Dakota" = "ND",
  "Ohio" = "OH",
  "Oklahoma" = "OK",
  "Oregon" = "OR",
  "Pennsylvania" = "PA",
  "Rhode Island" = "RI",
  "South Carolina" = "SC",
  "South Dakota" = "SD",
  "Tennessee" = "TN",
  "Texas" = "TX",
  "Utah" = "UT",
  "Vermont"	= "VT",
  "Virginia" = "VA",
  "Washington" = "WA",
  "West Virginia" = "WV",
  "Wisconsin" = "WI",
  "Wyoming"	= "WY"
)

state_latlong = read.csv("state_latlong.csv", stringsAsFactors = F, header = T)

shinyApp(
  ui = navbarPage("US Wildfires", id="nav",

    tabPanel("Interactive map",
      div(class="outer",
  
        tags$head(includeCSS("styles.css")),
  
        # If not using custom CSS, set height of leafletOutput to a number instead of percent
        leafletOutput("map", width="100%", height="100%"),
  
        absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
          draggable = TRUE, top = 60, left = "auto", right = 10, bottom = "auto",
          width = 330, height = "auto",
  
          h3("US Wildfires explorer"),
  
          selectInput("basemap", "Base Map", maps),
          selectInput("state", "States", states, selected = "All"),
          dateInput("datefrom", "Select the Start Date", value = "2015-12-15", min = "1992-01-01", max = "2015-12-31"),
          dateInput("dateto", "Select the End Date", value = "2015-12-31", min = "1992-01-01", max = "2015-12-31"),
          actionButton("button", "Search")
        ),
        absolutePanel(id = "plots", class = "panel panel-default", fixed = TRUE,
          draggable = TRUE, top = 60, left = 10, right = "auto", bottom = "auto",
          width = 400, height = "auto",
                    
          h3("Plot Explorer"),
          
          plotOutput("plot1", height = 200),
          plotOutput("plot2", height = 300)
        ),
  
        tags$div(id="cite",
          tags$em('Short, Karen C. 2017. Spatial wildfire occurrence data for the United States, 1992-2015 [FPA_FOD_20170508]. 4th Edition. Fort Collins, CO: Forest Service Research Data Archive. https://doi.org/10.2737/RDS-2013-0009.4')
        )
      )
    ),
  
    tabPanel("Data explorer"
    ),
  
    conditionalPanel("false", icon("crosshair"))
  )
  ,
  server = function(input, output, session){
    
    observeEvent(input$button,{
      
      fires.df = fires %>% filter((input$datefrom <= DISCOVERY_DATEymd)&(DISCOVERY_DATEymd <= input$dateto))
      if (input$state != "All"){
        fires.df = fires.df %>% filter(STATE == input$state)
      }
      
      popups.df = fires.df %>% 
        mutate(pop = paste(paste0("<b>", FOD_ID,"</b>"),
                           paste0("Discovery Date: ", DISCOVERY_DATEymd),
                           paste0("Latitude: ", LATITUDE),
                           paste0("Longitude: ", LONGITUDE),
                           paste0("Fire Size: ", FIRE_SIZE),
                           paste0("Fire Class: ", FIRE_SIZE_CLASS),
                           paste0("Cause: ", STAT_CAUSE_DESCR),
                           sep = "<br/>")) %>% 
        select(LONGITUDE, LATITUDE, pop)
      
      output$plot1 <- renderPlot({
        ggplot(fires.df, aes(x = DISCOVERY_DATEymd, y = FIRE_SIZE)) + 
          geom_point(col = "purple") +
          labs(title = "Fire Size by Date",x = "Date",
               y = "Fire Size (acres)") + theme_bw()
      })
      
      output$plot2 <- renderPlot({
        fires.df %>% group_by(STAT_CAUSE_DESCR) %>%
          summarize(total_size = sum(FIRE_SIZE, na.rm = TRUE)) %>%
          ggplot(aes(x = STAT_CAUSE_DESCR, y = total_size)) + 
          geom_bar(stat = 'identity', fill = 'orange') +
          labs(title = "Total Wildfire Size by Cause",x = "Cause",
               y = "Fire Size (acres)") + theme_bw() +
          theme(axis.text.x = element_text(angle = 90, hjust = 1))
      })
      
      
      stateBy = input$state
      mapBy = input$basemap
      
      maplat = 37.45 
      maplong = -93.85
      zoom = 4
      
      if (stateBy != "All"){
        maplat = state_latlong$Latitude[state_latlong$State == stateBy]
        maplong = state_latlong$Longitude[state_latlong$State == stateBy]
        zoom = 6
      }
      
      if (mapBy == "default")
      {
        output$map <- renderLeaflet({
          leaflet() %>% setView(lng = maplong, lat = maplat, zoom = zoom) %>%
            addTiles() %>% 
            addMarkers(lng = ~LONGITUDE, lat = ~LATITUDE, popup = ~pop, data = popups.df)  })
      }
      else{
        output$map <- renderLeaflet({
          leaflet() %>% setView(lng = maplong, lat = maplat, zoom = zoom) %>%
            addProviderTiles(mapBy,
                              options = providerTileOptions(noWrap = TRUE)) %>%
            addMarkers(lng = ~LONGITUDE, lat = ~LATITUDE, popup = ~pop, data = popups.df) })
      }
    })
    
  }
)
```